### ISSUE TITLE
Inconsistencies/Improvements

### ISSUE THREAD

**Issue by Jancso** [acqdiv/corpus_manual#3]
> Omissions are completely ignored in the ACQDIV Corpus (i.e. the omitted target word is not represented at all) because they are rare and considered to be speculative.

Omissions are kept in the actual and target form (e.g. Cree, 17-A1-2006-06-02ms u438)

> utterances.utterance raw is cleaned of any remaining punctuation and other special
> markers (cf. the transcription conventions); the new content is put into utterances.utterance.

It's not clear what is cleaned in utterance_raw (should there be any cleaning at all?)
- In CHAT, utterance terminators, separators, prosody and tone markers are removed from utterance_raw
- In Toolbox, however, utterance terminators and separators are kept in utterance_raw (e.g. Indonesian, 736551094519120405 (test DB))

> CHAT’s Local Events have been transferred to the comment tier (concatenating them to any pre-existing material). Where the utterance only consists of an event, the sentence type has been set to “action”.

No transfer to comment tier, sentence_type not set to 'action' (e.g. Inuktitut, u709 (test DB))

CHAT copora have highly specific sentence_types as opposed to Toolbox copora -> I think this is worth mentioning.

> Inuktitut has a special sentence type “broken for coding”, which indicates that there is no
> gloss but does not say anything about the sentence type. A warning “not glossed” is inserted
> into the corpus object and the sentence type is set to “default”.

Most of those cases don't look to me broken for glosses (e.g. u770, SUP51WM). In the CHAT manual, this is described as a special utterance terminator (-> transciption break).

> Replacements may occur in //u/w or in //u/g with a <w> sibling. Shortenings are in //u/w
> or in //u/g/w. (p.65)

not corpus-specific, removal

> 1 for utterances directed to a target child, 0 for all others (including unknown addressees)

unknown addressees are nulled in the DB

Note: this list might be growing as we start refactoring the CHAT XML pipeline.

**Comment by Jancso** [comment]
Cree:
- No phonetic transcriptions are used at the moment
- 'missingortho' not attested
- square brackets only occur around morphology tiers (not on the main line!)
- numbers connected by spaces and a greater than sign are not attested

**Comment by bambooforest** [comment]
Issue moved to dev version.
